[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
rpg = "7ZrKbLU5nsU6Pyyj9TtVYT8WdrEbiCjeTD7C5Brfgcrf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
